### ISSUE TITLE
请问什么时候可以分享一下代码，向大佬学习！

### ISSUE THREAD

**Issue by lzw0515** [AIDefender/ReMERN-ReMERT#1]

**Comment by AIDefender** [comment]
感谢关注！我最近比较忙qaq，三四月份会整理好。Unofficial code可以看 https://github.com/AIDefender/MyDiscor
Thanks for the attention. I have been busy these days and the official code will be released two or three months later. Check the unofficial code at https://github.com/AIDefender/MyDiscor if you will.
