### ISSUE TITLE
请问什么时候可以分享一下代码，向大佬学习！

### ISSUE THREAD

**Issue by zzhuncle** [AIDefender/ReMERN-ReMERT#2]
请问什么时候可以分享一下代码，向大佬学习，毕业设计希望能够参考一下！

**Comment by AIDefender** [comment]
Please check the preliminary code at https://github.com/AIDefender/MyDiscor. Algorithm details can be found at https://github.com/AIDefender/MyDiscor/blob/master/discor/algorithm/discor.py. Thank you.
