### ISSUE TITLE
How to compute w_k in ReMERN and ReMERT?

### ISSUE THREAD

**Issue by qlan3** [AIDefender/ReMERN-ReMERT#3]
Hi, I'm wondering how to compute $w_k$ in your two algorithms ReMERN and ReMERT? Specifically, how to compute $d^{\pi_k(s,a)} / \mu(s,a)$? Can you please point me to the relevant code in your unofficial repo for this part?

**Comment by AIDefender** [comment]
Hello. You can check line 108-134 of https://github.com/AIDefender/MyDiscor/blob/master/discor/algorithm/discor.py. Basically we are doing classification between samples from the slow and the fast buffer. It can be found in the paper "Experience Replay with Likelihood-free Importance Weights" (chapter 4) why this is an approximation of $d^{\pi_k(s,a)} / \mu(s,a)$.

**Comment by qlan3** [comment]
Thanks!
